### ISSUE TITLE
ObjectID's not supported - UnknownTypeError: oid

### ISSUE THREAD

**Issue by Vivalldi** [lyschoening/meteor-ejson-python#4]
Meteor allows for Mongo Object id. The DDP client will receive something such as 

<pre>
{  
   "msg":"added",
   "collection":"stores",
   "id":"2bd954daf1323b426c438f11",
   "fields":{  
      "name":"Nike",
      "logo":"/images/partner-icons/nike.png",
      "link":"nike",
      "topMaleProducts":[  
         {  
           <b>"$type":"oid"</b>,
            "$value":"57b763d5fe40b652b9e75f92"
         },
         {  
           <b>"$type":"oid"</b>,
            "$value":"57b763d5fe40b652b9e7604d"
         },
         {  
           <b>"$type":"oid"</b>,
            "$value":"57b763d5fe40b652b9e75e33"
         },
         {  
            <b>"$type":"oid"</b>,
            "$value":"57b763d5fe40b652b9e7608c"
         }
      ],
      "topFemaleProducts":[  
         {  
           <b>"$type":"oid"</b>,
            "$value":"57b763d3fe40b652b9e758da"
         },
         {  
            <b>"$type":"oid"</b>,
            "$value":"57b763d3fe40b652b9e758b6"
         }
      ],
      "followerCount":2
   }
}
</pre>
when subscribing to a collection and then the meteor-ejson-python client attempts to parse the "$type" fields. Not entirely sure why. 

I'll paste the entire error, but it really does boil down to the type being parsed

```
Exception in thread WebSocketClient:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Library/Python/2.7/site-packages/ws4py/websocket.py", line 506, in run
    if not self.once():
  File "/Library/Python/2.7/site-packages/DDPClient.py", line 53, in once
    return super(DDPSocket, self).once()
  File "/Library/Python/2.7/site-packages/ws4py/websocket.py", line 388, in once
    if not self.process(b):
  File "/Library/Python/2.7/site-packages/ws4py/websocket.py", line 458, in process
    self.received_message(s.message)
  File "/Library/Python/2.7/site-packages/DDPClient.py", line 41, in received_message
    self.emit('received_message', data)
  File "/Library/Python/2.7/site-packages/pyee/__init__.py", line 148, in emit
    result = f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/DDPClient.py", line 162, in received_message
    data = ejson.loads(str(data))
  File "/Library/Python/2.7/site-packages/ejson/__init__.py", line 132, in loads
    return json.loads(obj, *args, cls=kwargs.pop('cls', EJSONDecoder), **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/Library/Python/2.7/site-packages/ejson/__init__.py", line 126, in decode
    return self._decode(o)
  File "/Library/Python/2.7/site-packages/ejson/__init__.py", line 117, in _decode
    return {k: self._decode(v) for k, v in o.items()}
  File "/Library/Python/2.7/site-packages/ejson/__init__.py", line 117, in <dictcomp>
    return {k: self._decode(v) for k, v in o.items()}
  File "/Library/Python/2.7/site-packages/ejson/__init__.py", line 117, in _decode
    return {k: self._decode(v) for k, v in o.items()}
  File "/Library/Python/2.7/site-packages/ejson/__init__.py", line 117, in <dictcomp>
    return {k: self._decode(v) for k, v in o.items()}
  File "/Library/Python/2.7/site-packages/ejson/__init__.py", line 111, in _decode
    raise UnknownTypeError(o["$type"])
UnknownTypeError: oid
```

**Comment by lyschoening** [comment]
ObjectIDs are a user-defined EJSON type. You'll need to set up a "oid" type hook for this:

```
ejson.loads(v, custom_type_hooks=[('oid', ObjectId)])
```

Read more here: https://github.com/lyschoening/meteor-ejson-python#advanced-usage
